################
# continuous recording
continuous_topics: [/tf, /joint_states, /spacenav/offset, /spacenav/rot_offset]

################
# triggered recording
trigger_topics: [] 

# setup time trigger
trigger_timestep: 10

# setup tf triggers
trigger_record_translation: 0.5
trigger_record_rotation: 0.1
wanted_tfs:
 - reference_frame: /map
   target_frame: /base_link
   trigger_record_translation: 0.05
   trigger_record_rotation: 0.05
 - reference_frame: /base_link
   target_frame: /sdh_palm_link
   trigger_record_translation: 0.05
   trigger_record_rotation: 0.05
 - reference_frame: /map
   target_frame: /rviz_cam
   trigger_record_translation: 0.05
   trigger_record_rotation: 0.05
