################
# continuous recording
continuous_topics: [/tf, /joint_states, /spacenav/offset, /spacenav/rot_offset, /spacenav/joy]

################
# triggered recording
trigger_topics: [/cam3d_throttled/rgb/image_color, /cam3d_throttled/depth_registered/points, /map]

# setup time trigger
trigger_timestep: 10

# setup tf triggers
trigger_record_translation: 0.5
trigger_record_rotation: 0.1
wanted_tfs:
 - reference_frame: /map
   target_frame: /base_link
   trigger_record_translation: 0.5
   trigger_record_rotation: 0.1
